# Generated by Django 6.0.2 on 2026-04-10 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_fcm_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessGrant',
        ),
    ]
