# Generated by Django 6.0.2 on 2026-03-04 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicament_name', models.CharField(max_length=255)),
                ('forme', models.CharField(max_length=100)),
                ('dosage', models.IntegerField()),
                ('matin', models.BooleanField(default=False)),
                ('midi', models.BooleanField(default=False)),
                ('soir', models.BooleanField(default=False)),
                ('semaine', models.BooleanField(default=False)),
                ('duree', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
