# Generated by Django 6.0.2 on 2026-03-10 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
