# Generated by Django 6.0.2 on 2026-03-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='created_by',
            field=models.CharField(default='professionnel', max_length=100),
        ),
    ]
