# Generated by Django 6.0.2 on 2026-03-13 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='created_by',
        ),
    ]
